sudo: false
language: scala

before_script: travis_retry sbt -Dinclude.from.github=true ++$TRAVIS_SCALA_VERSION update

script:
  - sbt -Dinclude.from.github=true ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
  - sbt coveralls

scala:
  - 2.12.3
jdk:
  - oraclejdk8

branches:
  only:
    # We're only building these branches and pull requests.
    - master
    - develop
#notifications:
#  slack: ???